import{A as n}from"./assets/vendor-3f3e8d2c.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const i of t)if(i.type==="childList")for(const l of i.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function a(t){const i={};return t.integrity&&(i.integrity=t.integrity),t.referrerPolicy&&(i.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?i.credentials="include":t.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function o(t){if(t.ep)return;t.ep=!0;const i=a(t);fetch(t.href,i)}})();const u=r=>{const s=document.querySelector(".hero_inner"),a=r.map(o=>`
      <div class="hero_item">
        <h2 class="hero_item_title">${o.title}</h2>
        <a target = "_blank" class="hero_item_link hero_item_deploy" href="${o.urlDeploy}" class="btn">View Project</a>
        <a target = "_blank" class="hero_item_link hero_item_file" href="${o.urlFiles}" class="btn">View Files</a>
        <img class="hero_item_image" src="${o.img}" alt="${o.title}" />
      </div>
    `).join("");s.innerHTML=a},g="/Porfolio/assets/1-afa84062.png",c="/Porfolio/assets/2-5a73a929.png",p="/Porfolio/assets/3-8a34a3da.png",h="/Porfolio/assets/4-4c04b4e0.png",f="/Porfolio/assets/5-5cb42bf6.png",m="/Porfolio/assets/6-6c5b4bd2.png",d="/Porfolio/assets/7-a7c0f83d.png",b="/Porfolio/assets/8-69b112a0.png",y="/Porfolio/assets/9-5e40a638.png",D="/Porfolio/assets/10-9a56c552.png",P="/Porfolio/assets/11-c82dd33d.png",S="/Porfolio/assets/12-17974d08.png",F="/Porfolio/assets/13-3ce0d3ee.png",G="/Porfolio/assets/14-ce59827e.png",_="/Porfolio/assets/15-085e1d36.png",e=[g,c,p,h,f,m,d,b,y,D,P,S,F,G,_],x=[{title:"Donut",urlDeploy:"https://sangarix.github.io/Donut/",urlFiles:"https://github.com/SanGariX/Donut",img:e[0]},{title:"BlogYo",urlDeploy:"https://sangarix.github.io/BlogYo/",urlFiles:"https://github.com/SanGariX/BlogYo",img:e[1]},{title:"BlogSE",urlDeploy:"https://sangarix.github.io/BlogSE/",urlFiles:"https://github.com/SanGariX/BlogSE",img:e[2]},{title:"Globe Attack",urlDeploy:"https://sangarix.github.io/Globe_Attack/",urlFiles:"https://github.com/SanGariX/Globe_Attack",img:e[3]},{title:"Dynasty Legends",urlDeploy:"https://sangarix.github.io/Dynasty_Legends/",urlFiles:"https://github.com/SanGariX/Dynasty_Legends",img:e[4]},{title:"Maze 3D",urlDeploy:"https://sangarix.github.io/Maze_3D/",urlFiles:"https://github.com/SanGariX/Maze_3D",img:e[5]},{title:"Perfffeto",urlDeploy:"https://sangarix.github.io/Perfffeto/",urlFiles:"https://github.com/SanGariX/Perfffeto",img:e[6]},{title:"GoGo",urlDeploy:"https://sangarix.github.io/GoGo/",urlFiles:"https://github.com/SanGariX/GoGo",img:e[7]},{title:"-eri-in-Parlas-n ",urlDeploy:"https://sangarix.github.io/-eri-in-Parlas-n/",urlFiles:"https://github.com/SanGariX/-eri-in-Parlas-n ",img:e[8]},{title:"Super-Tiles",urlDeploy:"https://sangarix.github.io/Super-Tiles/",urlFiles:"https://github.com/SanGariX/Super-Tiles",img:e[9]},{title:"Antikutlama",urlDeploy:"https://sangarix.github.io/Antikutlama/",urlFiles:"https://github.com/SanGariX/Antikutlama",img:e[10]},{title:"FunWayAbout",urlDeploy:"https://sangarix.github.io/FunWayAbout/",urlFiles:"https://github.com/SanGariX/FunWayAbout",img:e[11]},{title:"NewBasicInfo",urlDeploy:"https://sangarix.github.io/NewBasicInfo/",urlFiles:"https://github.com/SanGariX/NewBasicInfo",img:e[12]},{title:"FUN thesite",urlDeploy:"https://sangarix.github.io/FUN_thesite/",urlFiles:"https://github.com/SanGariX/FUN_thesite",img:e[13]},{title:"BestMainAbout",urlDeploy:"https://sangarix.github.io/BestMainAbout/",urlFiles:"https://github.com/SanGariX/BestMainAbout",img:e[14]}];document.addEventListener("DOMContentLoaded",({target:r})=>{document.querySelector(".wrapper").classList.add("loaded")});document.addEventListener("DOMContentLoaded",()=>{n.init({once:!0,duration:400,offset:80})});u(x);
//# sourceMappingURL=commonHelpers.js.map
